### ISSUE TITLE
Doc comments?

### ISSUE THREAD

**Issue by tmpfs** [someguynamedjosh/ouroboros#110]
The documentation comment when using `self_referencing` is always "The self-referencing struct." event when I apply a doc comment above the attribute.

Is there a trick to get it to respect my doc comment?

**Comment by someguynamedjosh** [comment]
It is recommended to wrap the generated struct in a new struct to provide a
clearer interface to whoever uses the code. You could then put the
documentation on the wrapper.

**Comment by tmpfs** [comment]
Thanks, i will do that then 👍
